CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    categoria VARCHAR(20) NOT NULL CHECK (categoria IN ('COMUM','PREMIUM','SUPER')),
    data_nascimento DATE NOT NULL,
    usuario_id BIGINT NOT NULL UNIQUE,
	PRIMARY KEY (id),
    CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);