CREATE TABLE IF NOT EXISTS cartao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_cartao VARCHAR(31) NOT NULL CHECK (tipo_cartao IN ('CREDITO', 'DEBITO')),
    numero_cartao VARCHAR(255) NOT NULL UNIQUE,
    conta_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    senha VARCHAR(255) NOT NULL,
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    taxa_utilizacao NUMERIC(5,4),
	limite NUMERIC(19,2),
	limite_atual NUMERIC(19,2),

    -- CREDITO
    total_fatura NUMERIC(19,2),
    total_fatura_paga NUMERIC(19,2),

	PRIMARY KEY (id),
    CONSTRAINT fk_cartao_conta FOREIGN KEY (conta_id) REFERENCES conta(id)
);