CREATE TABLE IF NOT EXISTS seguro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_seguro VARCHAR(20) NOT NULL CHECK (tipo_seguro IN ('FRAUDE','VIAGEM')),
    num_apolice VARCHAR(50) NOT NULL UNIQUE,
    cartao_id BIGINT NOT NULL,
    data_contratacao DATE NOT NULL,
    valor_apolice NUMERIC(19,2) NOT NULL,
    descricao_condicoes VARCHAR(300),
    premio_apolice NUMERIC(19,2) NOT NULL,
    status_seguro VARCHAR(50),
    data_acionamento DATE,
    valor_fraude NUMERIC(19,2),
	PRIMARY KEY (id),
    CONSTRAINT fk_seguro_cartao FOREIGN KEY (cartao_id) REFERENCES cartao(id)
);