CREATE TABLE IF NOT EXISTS politica_de_taxas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria VARCHAR(20) NOT NULL CHECK (categoria IN ('COMUM','PREMIUM','SUPER')),
    tarifa_manutencao_mensal_conta_corrente NUMERIC(10,2),
    rendimento_percentual_mensal_conta_poupanca NUMERIC(10,5),
    tarifa_manutencao_conta_internacional NUMERIC(10,2),
    limite_cartao_credito NUMERIC(19,2),
    limite_diario_debito NUMERIC(19,2),
    tarifa_seguro_viagem NUMERIC(10,2),
    tarifa_seguro_fraude NUMERIC(10,2),
	valor_apolice_fraude NUMERIC(10,2),
	valor_apolice_viagem NUMERIC(10,2),
	PRIMARY KEY (id)
);